language: python
matrix:
  include:
    - python: "2.7"

virtualenv:
  system_site_packages: true

before_install:
 - sudo apt-get install -qq python-numpy python-scipy

before_script:
  - python ./setup.py install
script: python ./unittests/run_tests.py $TEST_SUITE